baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Recipes'

[params]
  description = 'A personal collection of favorite recipes'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
