baseURL = 'https://rubenoost.github.io/recipes/'
languageCode = 'nl'
title = 'Kookboek Familie Oost'

[params]
  description = 'Onze favoriete recepten verzameld'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
