baseURL = 'https://recepten.oost.io/'
languageCode = 'nl'
title = 'Kookboek Familie Oost'

[params]
  description = 'Onze favoriete recepten verzameld'

[taxonomies]
  tag = 'tags'

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
